# Generated by Django 4.2.1 on 2023-06-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_user'),
        ('cart', '0004_remove_cart_customer_cart_user'),
    ]

    operations = [
    ]
