# Generated by Django 4.2.1 on 2023-06-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customer_photo'),
        ('user', '0002_alter_retailer_accepts_custom_order'),
    ]

    operations = [
    ]
