# Generated by Django 4.2.1 on 2023-06-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_retailer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_revenue_last_year', models.FloatField()),
                ('annual_revenue_this_year', models.FloatField()),
                ('monthly_revenue', models.FloatField()),
                ('number_of_orders_completed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RetailerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.analytics')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.retailer')),
            ],
        ),
    ]
