# Generated by Django 4.2.1 on 2023-06-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_retailer_photo'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='number_of_products_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.retailer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analytics',
            name='annual_revenue_last_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='annual_revenue_this_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='monthly_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='number_of_orders_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RetailerAnalytics',
        ),
    ]
