# Generated by Django 4.2.1 on 2023-06-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_retailer_photo'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotification',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retailernotification',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.retailer'),
            preserve_default=False,
        ),
    ]
