# Generated by Django 4.2.1 on 2023-06-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_product_size'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
