# Generated by Django 4.2.1 on 2023-06-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_totalprice_alter_order_shippingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='procuct',
            new_name='product',
        ),
    ]
