# Generated by Django 4.2.1 on 2023-06-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_customorder_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='size',
            field=models.CharField(default='46-20-145 B40-Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='46-20-145 B40-Medium', max_length=20),
        ),
    ]
