# Generated by Django 4.2.1 on 2023-06-24 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_shippingaddress_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='paidAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
