# Generated by Django 4.2.1 on 2023-06-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_customorder_paidat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='paidAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paidAt',
        ),
    ]
