# Generated by Django 4.2.1 on 2023-06-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_customorder_size_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
