# Generated by Django 4.2.1 on 2023-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_commisionprice_customorder_commissionprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='readyAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
