# Generated by Django 4.2.1 on 2023-06-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_customorder_readyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='paidAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
