# Generated by Django 4.2.1 on 2023-06-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_customorder_paidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commissionPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='commissionRate',
            field=models.CharField(default='2%', max_length=5),
        ),
    ]
