# Generated by Django 4.2.1 on 2023-06-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_commissionprice_order_commissionrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='delivery',
            field=models.CharField(choices=[('GO Delivery Ethiopia', 'GO Delivery Ethiopia'), ('WeDeliver', 'WeDeliver'), ('Eshi Express', 'Eshi Express'), ('Awra Delivery', 'Awra Delivery')], default='GO Delivery Ethiopia', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('GO Delivery Ethiopia', 'GO Delivery Ethiopia'), ('WeDeliver', 'WeDeliver'), ('Eshi Express', 'Eshi Express'), ('Awra Delivery', 'Awra Delivery')], default='GO Delivery Ethiopia', max_length=20),
        ),
    ]
