# Generated by Django 4.2.1 on 2023-06-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_retailer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_customers', models.IntegerField()),
                ('number_of_retailers', models.IntegerField()),
                ('total_number_of_products', models.IntegerField(default=0)),
                ('total_number_of_orders', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.IntegerField(default=0)),
                ('total_number_of_products', models.IntegerField(default=0)),
                ('total_number_of_orders', models.IntegerField(default=0)),
                ('total_number_of_transaction', models.IntegerField(default=0)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.retailer')),
            ],
        ),
    ]
