# Generated by Django 4.2.1 on 2023-06-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_year_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_orders_completed', models.IntegerField(default=0)),
                ('total_number_of_transaction', models.IntegerField(default=0)),
                ('monthly_revenues', models.TextField(default='[]')),
                ('number_of_products', models.IntegerField(default=0)),
            ],
        ),
    ]
