# Generated by Django 4.2.1 on 2023-06-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RenameField(
            model_name='salesreport',
            old_name='number_of_products',
            new_name='number_of_orders_completed',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='total_number_of_orders',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='total_number_of_products',
        ),
        migrations.AddField(
            model_name='salesreport',
            name='current_year_annual_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='last_year_annual_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='monthly_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
