# Generated by Django 4.2.1 on 2023-06-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_delete_report_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesreport',
            old_name='current_year_annual_revenue',
            new_name='current_year_revenue',
        ),
        migrations.RenameField(
            model_name='salesreport',
            old_name='last_year_annual_revenue',
            new_name='last_year_revenue',
        ),
    ]
