# Generated by Django 4.2.1 on 2023-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_salesreport_monthly_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='monthly_revenue',
        ),
        migrations.AddField(
            model_name='salesreport',
            name='monthly_revenues',
            field=models.JSONField(default=list),
        ),
    ]
