# Generated by Django 4.2.1 on 2023-06-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_salesreport_monthly_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='number_of_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='monthly_revenues',
            field=models.TextField(default='[]'),
        ),
    ]
