# Generated by Django 4.2.1 on 2023-06-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
