# Generated by Django 4.2.1 on 2023-06-16 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Aviator', 'Aviator'), ('Wayfarer', 'Wayfarer'), ('Round', 'Round'), ('Cat Eye', 'Cat Eye'), ('Sports', 'Sports'), ('Oversized', 'Oversized'), ('Mirrored', 'Mirrored'), ('Polarized', 'Polarized'), ('Gradient', 'Gradient'), ('Clip-On', 'Clip-On')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='photo', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
    ]
