# Generated by Django 4.2.1 on 2023-06-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_product_photo_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
