# Generated by Django 4.2.1 on 2023-06-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_isfavourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isFavourite',
        ),
    ]
