# Generated by Django 4.2.1 on 2023-06-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Aviator', 'Aviator'), ('Wayfarer', 'Wayfarer'), ('Round', 'Round'), ('Cat Eye', 'Cat Eye'), ('Sports', 'Sports'), ('Oversized', 'Oversized'), ('Mirrored', 'Mirrored'), ('Polarized', 'Polarized'), ('Gradient', 'Gradient'), ('Clip-On', 'Clip-On')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
