# Generated by Django 4.2.1 on 2023-06-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
