# Generated by Django 4.2.1 on 2023-06-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_reserved_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retailer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.retailer')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
