# Generated by Django 4.2.1 on 2023-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='name',
            field=models.CharField(default='Vision EyeGlass Shopping', max_length=255),
        ),
    ]
